# Generated by Django 5.2.4 on 2025-07-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_vulnerablemachine_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerablemachine',
            name='security_tools',
            field=models.TextField(blank=True, null=True, verbose_name='Средства защиты'),
        ),
        migrations.AddField(
            model_name='vulnerablemachine',
            name='software_versions',
            field=models.TextField(blank=True, null=True, verbose_name='Версии ПО'),
        ),
        migrations.AlterField(
            model_name='vulnerablemachine',
            name='tags',
            field=models.TextField(verbose_name='Теги (уязвимости)'),
        ),
    ]
