# Generated by Django 5.2.4 on 2025-07-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_vulnerablemachine_security_tools_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerablemachine',
            name='status',
            field=models.CharField(default='Используется', max_length=50, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='vulnerablemachine',
            name='type',
            field=models.CharField(choices=[('ready', 'Готовая'), ('idea', 'Идея')], default='ready', max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='vulnerablemachine',
            name='security_tools',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Средства защиты'),
        ),
        migrations.AlterField(
            model_name='vulnerablemachine',
            name='software_versions',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Версии ПО'),
        ),
        migrations.AlterField(
            model_name='vulnerablemachine',
            name='tags',
            field=models.CharField(max_length=255, verbose_name='Теги (уязвимости)'),
        ),
    ]
