# Generated by Django 5.2.4 on 2025-07-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_vulnerablemachine_status_vulnerablemachine_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerablemachine',
            name='software_versions',
        ),
        migrations.AlterField(
            model_name='vulnerablemachine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
