# Generated by Django 5.2.4 on 2025-07-09 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_remove_software_versions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerablemachine',
            name='is_used',
        ),
    ]
